chat/urls.py
from django.urls import include, path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('chat/', views.ChatView.as_view(), name='chat'),
    path('supports/', views.SupportView.as_view(), name='supports'),
    path('supports/create/', views.CreateSupportView.as_view(), name='supcreate'),
    path('supports/edit/<int:sup_id>', views.EditSupportView.as_view(), name='supedit'),
    path('supports/delete/<int:sup_id>', views.DeleteSupportView.as_view(), name='supdelete'),
    path('faq/', views.FaqView.as_view(), name='faq')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls'))
]

chat/models.py
from django.db import models

class Support(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    key_words = models.TextField()

chat/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import JsonResponse
from .models import Support

class IndexView(View):
    """Главная страница"""
    def get(self, request):
        template_name = 'chat/index.html'
        return render(request, template_name)


class ChatView(View):
    """Страница чата"""
    template_name = 'chat/chat.html'
    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        user_message = request.POST['user-message']
        if user_message == "Привет!":
            return JsonResponse({'UserMessage':user_message, 'BotMessage':'Привет :)'})
        elif user_message == "Как дела?":
            return JsonResponse({'UserMessage':user_message, 'BotMessage':'Замечательно!'})
        else:
            return JsonResponse({'UserMessage':user_message, 'BotMessage':'Непонятный для меня запрос :('})


class FaqView(View):
    """FAQ страница"""
    def get(self, request):
        template_name = 'chat/faq.html'
        return render(request, template_name)


class SupportView(View):
    """Страница просмотра саппортов"""
    def get(self, request):
        template_name = 'chat/supports.html'
        supports = Support.objects.all()
        return render(request, template_name, {'supports':supports})


class CreateSupportView(View):
    """Страница создания саппортов"""
    def get(self, request):
        template_name = 'chat/supcreate.html'
        return render(request, template_name)

    def post(self, request):
        name = request.POST['name']
        description = request.POST['description']
        key_words = request.POST['key_words']

        Support.objects.create(
            name=name,
            description=description,
            key_words=key_words
        )
        return redirect('chat:supports')


class EditSupportView(View):
    """Страница изменения саппортов"""
    def get(self, request, sup_id):
        template_name = 'chat/supedit.html'
        support = Support.objects.get(pk=sup_id)
        return render(request, template_name, {'support':support})

    def post(self, request, sup_id):
        support = Support.objects.get(pk=sup_id)

        support.name = request.POST['name']
        support.description = request.POST['description']
        support.key_words = request.POST['key_words']
        support.save()

        return redirect('chat:supports')


class DeleteSupportView(View):
    """Страница удаления саппортов"""
    def get(self, request, sup_id):
        template_name = 'chat/supdelete.html'
        support = Support.objects.get(pk=sup_id)
        return render(request, template_name, {'support':support})

    def post(self, request, sup_id):
        support = Support.objects.get(pk=sup_id)
        support.delete()
        return redirect('chat:supports')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="{% static 'img/logo.png' %}" />
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/site.css' %}">
    <script src="{% static '/bootstrap/js/jquery.js' %}"></script>
    <script src="{% static '/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/site.js' %}"></script>
    <title>Chatbot</title>
</head>
<body>
    <div style="border:none; border-radius: 0;"  class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbar-main">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'chat:index' %}">
                        <img style="height:40px; margin-top: -10px;" src="/static/img/logo.png">
                    </a>
                </div>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'chat:index' %}">Главная</a></li>
                    <li><a href="{% url 'chat:chat' %}">Чат</a></li>
                    <li><a href="{% url 'chat:supports' %}">Саппорты</a></li>
                    <li><a href="{% url 'chat:faq' %}">FAQ</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/chat/chat.html
{% extends "base.html" %}

{% block content %}
<div class="chat-window disable-scrollbars">
    <div class="message">
        <div class="bot-message">
            <p>
                Бот: Вас приветствует бот Джимми :)
                Введите, пожалуйста, интересущий вас вопрос ниже, и я постараюсь на него ответить.
            </p>
        </div>
    </div>
</div>
<div class="input-group">
    {% csrf_token %}
    <input id="user-message" name="user-message" class="form-control" placeholder="Write a message">
    <span class="input-group-btn">
        <button id="send-message" class="btn btn-primary" type="submit">Отправить</button>
    </span>
</div>
{% endblock %}

templates/chat/faq.html
{% extends "base.html" %}

{% block content %}
    <section class="faq-promo">
        <p class="small-title">
            F.A.Q.
        </p>
        <h1 class="main-title faq-title">
            Here are some common questions about our bot
        </h1>
    </section>
    <section class="questions-block">
        <ul class="questions-list">
            <li class="question">Template</li>
            <li class="question">Template</li>
            <li class="question">Template</li>
            <li class="question">Template</li>
            <li class="question">Template</li>
        </ul>
    </section>
{% endblock %}

templates/chat/index.html
{% extends "base.html" %}

{% block content %}
<!-- <div style="text-align:center" class="starter-template">
    <h2>Наш чат-бот ответит на все ваши вопросы!</h2>
    <h3>Опишите проблему и чат-бот подскажет вам, что делать дальше</h3>
</div> -->
<section class="promo">
    <div class="left-column">
        <h1 class="main-title">
            Interactive chat-bot
        </h1>
        <p class="details">
            The bot receives user messages, analyzes them and issues a response that matches the user's request.
        </p>
        <a class="btn-link" href="{% url 'chat:chat' %}">Let's go!</a>
    </div>
</section>
{% endblock %}

templates/chat/supcreate.html
{% extends "base.html" %}

{% block content %}
    <h1>Добавить саппорта</h1>
    <form action="{% url 'chat:supcreate' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label>Имя</label>
            <input class="form-control" type="text" name="name" required>
        </div>
        <div class="form-group">
            <label>Описание</label>
            <input class="form-control" type="text" name="description" required>
        </div>
        <div class="form-group">
            <label>Ключевые слова через запятую</label>
            <textarea rows="5" class="form-control" name="key_words" required></textarea>
        </div>
        <input class="btn btn-primary" type="submit" value="Добавить">
    </form>
{% endblock %}

templates/chat/supdelete.html
{% extends "base.html" %}

{% block content %}
    <h1>Удалить саппорта #{{support.id}}</h1>
    <form action="{% url 'chat:supdelete' support.id %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="Удалить">
        <a href="{% url 'chat:supports' %}">Вернуться назад</a>
    </form>
{% endblock %}

templates/chat/supedit.html
{% extends "base.html" %}

{% block content %}
    <h1>Обновить саппорта #{{support.id}}</h1>
    <form action="{% url 'chat:supedit' support.id %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label>Имя</label>
            <input class="form-control" type="text" name="name" value="{{support.name}}" required>
        </div>
        <div class="form-group">
            <label>Описание</label>
            <input class="form-control" type="text" name="description" value="{{support.description}}" required>
        </div>
        <div class="form-group">
            <label>Ключевые слова через запятую</label>
            <textarea rows="5" class="form-control" name="key_words" required>{{support.key_words}}</textarea>
        </div>
        <input class="btn btn-primary" type="submit" value="Обновить">
        <a href="{% url 'chat:supports' %}">Вернуться назад</a>
    </form>
{% endblock %}

templates/chat/supports.html
{% extends "base.html" %}

{% block content %}
    <h1>Саппорты</h1>
    <a href="{% url 'chat:supcreate' %}">Добавить саппорта</a>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>№</th>
                    <th>Имя</th>
                    <th>Описание</th>
                    <th>Ключевые слова</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for support in supports %}
                    <tr>
                        <td>{{ support.id }}</td>
                        <td>{{ support.name }}</td>
                        <td>{{ support.description }}</td>
                        <td>{{ support.key_words }}</td>
                        <td>
                            <a href="{% url 'chat:supedit' support.id %}">Изменить</a> |
                            <a href="{% url 'chat:supdelete' support.id %}">Удалить</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/templates.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="{% static 'img/logo.png' %}" />
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/site.css' %}">
    <script src="{% static '/bootstrap/js/jquery.js' %}"></script>
    <script src="{% static '/bootstrap/js/bootstrap.min.js' %}"></script>
    <title>Chatbot</title>
</head>
<body>
    <div style="border:none; border-radius: 0;"  class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbar-main">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'chat:index' %}">
                        <img style="height:40px; margin-top: -10px;" src="/static/img/logo.png">
                    </a>
                </div>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'chat:index' %}">Главная</a></li>
                    <li><a href="{% url 'chat:chat' %}">Чат</a></li>
                    <li><a href="#">FAQ</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>